deploy:
  provider: heroku
  api_key:
    secure: hvPmsU6t32xgH3Lhtvh76LDKZlvyGPs01/2FA9yAoPK3O2QsN99cp+IVTK7NesEmrMAcxXxjoJ3GsXm7Pg/D8OJ+6/Q0hr5IM/b6kcW6XbMikrzg6qvVTKA9v682ImfnCsKSRqkltzojj6lAcVc8oBGTxENu0og2Ff+Yd8CZxBv6K0pivVisGkDVI4JCQmXC/k3bHsFYP7mpA8wRkFdnyO711GWbQOyBfW25rKYPqKwiCLfNBQCerd0BUfrX27UxmNL0BCyRtCfbOyrHNwWR4SUjPfGwJjLeDxyx37RuppJYQqxLH4Zwbz2QWMhK4yaNtaCjLF9lj6ac5ptgWIhPh9qgLGLYy++dpk9VZSTxajRRtYFYTBoI0nOf1TIXXpX38dDsZn/MhUJWpIH29eK0MQOLevRvthTD5mMkPvbJbwcxxgd4c5RYWueIIFsRGfpoDYYbiFn3qGhI9ekvKi2BiLadLuzABo5pmpy7c9Z9sax5zMEYpTn6ooJjCAlRrw01Y7PW+kw5pmXLITlzVRBtX8HdvKzj36mk9dmuSgkrC9tmCIc2s935gNfnIoM3DT4caUPIgAa5d4rUjNT78zgpKwHTMsb+vtSFETrT5C7Mg8ZX03EHFNl292ItAJI25/nXZFqRgiVmm14TosvraBFlS2BBnytKamVDtyCP3UEZQ94=
  app: unittest-travis-heroku
  on:
    repo: elogonme/unittest-travis-heroku
  skip_cleanup: 'true'
